### ISSUE TITLE
Problema com nome da pasta

### ISSUE THREAD

**Issue by felipemarinho97** [gabrielfern/automated-leda-tasks#3]
quero que fique Rxx-0x como faz?

**Comment by gabrielfern** [comment]
Acebei preferindo padronizar como Rxx, mas se vc preferir, altera nas seguintes linhas "roteiro[0:3]" por apenas "roteiro":
https://github.com/gabrielfern/automated-leda-tasks/blob/1.1.3/automated/__main__.py#L140
https://github.com/gabrielfern/automated-leda-tasks/blob/1.1.3/automated/__main__.py#L141
https://github.com/gabrielfern/automated-leda-tasks/blob/1.1.3/automated/__main__.py#L143
https://github.com/gabrielfern/automated-leda-tasks/blob/1.1.3/automated/__main__.py#L146
